### PR TITLE
[blog] Add post that avertises Cling definition shadowing

### PR DESCRIPTION
**Pull request by jalopezg-r00t**
This pull-request adds a blog post to advertise the Cling redefinition support, a.k.a., definition shadowing, which was released in ROOT 6.20.

### CODE REVIEW

File: blog/_posts/2021-06-07-cling-declshadow.md [hunk 1]
```diff
@@ -0,0 +1,48 @@
+---
+title: "Support for redefinitions in Cling, the ROOT's C++ interpreter"
```
Comment (eguiraud) [inline blog/_posts/2021-06-07-cling-declshadow.md:2]:
```suggestion
title: "Support for redefinitions in Cling, ROOT's C++ interpreter"
```

File: blog/_posts/2021-06-07-cling-declshadow.md [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+layout: archive
+author: Javier Lopez Gomez
+---
+
+One of the changes introduced in ROOT 6.20 was to allow users to provide a new definition of a function/variable/class that was already defined. Although ROOT already had two major releases since, we were missing a blog post to make this feature publicly known.
```
Comment (eguiraud) [inline blog/_posts/2021-06-07-cling-declshadow.md:7]: to me this reads a bit too apologetic, e.g. more positive: "Back in ROOT 6.20, we introduced a big quality-of-life improvement for interactive C++ usage: .... Since then, we made fine-tuned the feature and the feedback we gathered convinced us that it's time for the world to know about cling's shadowing feature!"

File: blog/_posts/2021-06-07-cling-declshadow.md [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+root [0] int i;
+root [1] double i = 1.0;
+input_line_4:2:9: error: redefinition of 'i' with different type: 'double' vs 'int'
+  double i = 1.0;
+         ^
+input_line_3:2:6: note: previous definition is here
+  int i;
+```
+
+While this behavior is expected from a ISO-compliant C++ compiler, it doesn't seem convenient for interpreted C++ where users expect a behavior closer to an scripting language, e.g. Python. This issue was specially visible in Jupyter notebooks, where cells that provided a definition couldn't be edited and re-run without restarting the C++ kernel. We knew it was annoying and we worked on it for the 6.20 release.
```
Comment (eguiraud) [inline blog/_posts/2021-06-07-cling-declshadow.md:20]:
```suggestion
While this behavior is expected from a ISO-compliant C++ compiler, it doesn't seem convenient for interpreted C++ where users expect a behavior closer to a scripting language like Python. This issue was especially visible in Jupyter notebooks, where cells that provided a definition couldn't be edited and re-run without restarting the C++ kernel. We knew it was annoying and we fixed it in the 6.20 release.
```

File: blog/_posts/2021-06-07-cling-declshadow.md [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+root [4] i(3.141592653)
+(double) 2.1415927
+```
+
+However if you are using Cling standalone, this feature is considered optional and thus disabled at startup. In any case, you can manually turn it on/off as follows:
+```C++
+gClingOpts->AllowRedefinition = 1; // or 0 to disable
+```
+
+# TL:DR
```
Comment (eguiraud) [inline blog/_posts/2021-06-07-cling-declshadow.md:40]: This is more a technical overview than a TL;DR, maybe

```suggestion
# The gritty details
```
?

File: blog/_posts/2021-06-07-cling-declshadow.md [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+Formally, the ISO C++ one-definition-rule (ODR) forbids multiple definitions in order to ensure a consistent view of an entity across different translation units. The technique implemented in Cling does not, however, violate the ODR as each definition is internally enclosed in its own namespace. This ensures the uniqueness of the qualified (and mangled) name of each definition. The latest definition is made available on the global scope by fixing up the translation unit lookup table.
```
Comment (eguiraud) [inline blog/_posts/2021-06-07-cling-declshadow.md:41]:
```suggestion
Formally, the ISO C++ one-definition-rule (ODR) forbids multiple definitions in order to ensure a consistent view of an entity across different translation units. The technique implemented in Cling does not, however, violate the ODR as each definition is internally enclosed in its own namespace. This ensures the uniqueness of the qualified (and mangled) name of each definition. The latest definition is made available in the global scope by fixing up the translation unit lookup table.
```

File: blog/_posts/2021-06-07-cling-declshadow.md [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+
+For more information, you can refer to the [conference paper](https://dl.acm.org/doi/abs/10.1145/3377555.3377901) published in Proceedings 29th International Conference on Compiler Construction (CC 2020).
```
Comment (eguiraud) [inline blog/_posts/2021-06-07-cling-declshadow.md:43]:
```suggestion
For more information, you can refer to the [conference paper](https://dl.acm.org/doi/abs/10.1145/3377555.3377901) published in the Proceedings of the 29th International Conference on Compiler Construction (CC 2020).
```

File: blog/_posts/2021-06-07-cling-declshadow.md [hunk 7]
```diff
@@ -0,0 +1,48 @@
...
+
+## Summary
+This feature allows a user to redefine functions, variables, or classes declared within the same the interpreter session. We hope that our users will enjoy this as much as we enjoyed implementing it.
```
Comment (eguiraud) [inline blog/_posts/2021-06-07-cling-declshadow.md:46]:
```suggestion
This feature allows a user to redefine functions, variables, or classes declared within the same interpreter session. We hope that our users will enjoy this as much as we enjoyed implementing it.
```

**Review by eguiraud — COMMENTED** [review]
great read, I like this a lot. I added some suggestions while reading, feel free to integrate them or not.

File: blog/_posts/2021-06-07-cling-declshadow.md [hunk 8]
```diff
@@ -0,0 +1,48 @@
...
+While this behavior is expected from a ISO-compliant C++ compiler, it doesn't seem convenient for interpreted C++ where users expect a behavior closer to a scripting language like Python. This issue was especially visible in Jupyter notebooks, where cells that provided a definition couldn't be edited and re-run without restarting the C++ kernel. We knew it was annoying and we fixed it in the 6.20 release.
+
+## Do I have to do anything to enable this?
+No. Support for redefinitions is automatically enabled for the ROOT prompt and Jupyter notebooks as of 6.20. Therefore, the following is now legal in a ROOT interpreter session:
+```C++
+root [0] int i = 0
+(int) 0
+root [1] double i = 1.0
+(double) 1.0000000
+root [2] // Note that `i` can be turn into a different thing, e.g. a function
```
Comment (Axel-Naumann) [inline blog/_posts/2021-06-07-cling-declshadow.md:29]:
```suggestion
root [2] // Note that `i` can become a different thing, e.g. a function
```

File: blog/_posts/2021-06-07-cling-declshadow.md [hunk 9]
```diff
@@ -0,0 +1,48 @@
...
+
+However if you are using Cling standalone, this feature is considered optional and thus disabled at startup. In any case, you can manually turn it on/off as follows:
+```C++
+gClingOpts->AllowRedefinition = 1; // or 0 to disable
+```
+
+# The gritty details
+Formally, the ISO C++ one-definition-rule (ODR) forbids multiple definitions in order to ensure a consistent view of an entity across different translation units. The technique implemented in Cling does not, however, violate the ODR as each definition is internally enclosed in its own namespace. This ensures the uniqueness of the qualified (and mangled) name of each definition. The latest definition is made available in the global scope by fixing up the translation unit lookup table.
+
+For more information, you can refer to the [conference paper](https://dl.acm.org/doi/abs/10.1145/3377555.3377901) published in the Proceedings of the 29th International Conference on Compiler Construction (CC 2020).
```
[the remark this answers is not in the document]
Comment (jalopezg-r00t) [reply blog/_posts/2021-06-07-cling-declshadow.md]: Done.  :-)
